Linux refactor
TheGameEngineers/PrimalPlus pull request #13
Opened 2023-03-31 12:32 UTC by ZackShrout

2023-03-31 16:09 UTC, Rashmatash reviewed
Looking good. I find a few things worth fixing,

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Graphics/GraphicsPlatform.cpp
> -        break;
This shouldn't fall through. It should just fail on non-Windows OS's.

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Graphics/Vulkan/VulkanCore.h
> +namespace primal::graphics::vulkan::core {
Oof! Formatting: no indents in namespace.

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Graphics/Vulkan/VulkanResources.h
>  bool create_framebuffer(VkDevice device, vulkan_renderpass& renderpass, u32 width, u32 height, u32 attach_count, utl::vector<VkImageView> attachments, vulkan_framebuffer& framebuffer);
I know this is not high performance path, but passing utl::vector by value might not be a good idea. It will create copy of the elements. Also, if you're passing attach_count anyway, why not pass attachments.data()?
If renderpass is not altered by this function, it should be a const ref.

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Graphics/Vulkan/VulkanResources.h
>  bool create_image(VkDevice device, VkImageType type, u32 width, u32 height, VkFormat format, VkImageTiling tiling, VkImageUsageFlags usage,
Putting these parameters in a struct image_init_info would be nicer.

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Input/InputLinux.cpp
> +	lk_mapping[platform::key_backspace] = input_code::code::key_backspace;
I don't think it's necessary to type ::code:: here (unless gcc would object).

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Input/InputLinux.cpp
> +		right_alt = 0x03,
right_alt = 0x04

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Input/InputLinux.cpp
> +	if (lk_mapping.find(key_sym) == lk_mapping.end())
return lk_mapping.count(key_sym) ? lk_mapping[key_sym] : u32_invalid_id;

;o)

2023-03-31 16:09 UTC, Rashmatash commented on Engine/Platform/X11Manager.h
> +    key_scrolllock = XK_Scroll_Lock,
I forgot tilde key (~)

2023-03-31 16:11 UTC, Rashmatash requested changes
Looking good! I found a few things worth fixing.

2023-03-31 22:53 UTC, ZackShrout commented on Engine/Graphics/GraphicsPlatform.cpp
> -        break;
Done

2023-03-31 22:56 UTC, ZackShrout commented on Engine/Graphics/Vulkan/VulkanCore.h
> +namespace primal::graphics::vulkan::core {
Done

2023-03-31 23:10 UTC, ZackShrout commented on Engine/Graphics/Vulkan/VulkanResources.h
>  bool create_framebuffer(VkDevice device, vulkan_renderpass& renderpass, u32 width, u32 height, u32 attach_count, utl::vector<VkImageView> attachments, vulkan_framebuffer& framebuffer);
Good point, done.

2023-03-31 23:23 UTC, ZackShrout commented on Engine/Graphics/Vulkan/VulkanResources.h
>  bool create_framebuffer(VkDevice device, vulkan_renderpass& renderpass, u32 width, u32 height, u32 attach_count, utl::vector<VkImageView> attachments, vulkan_framebuffer& framebuffer);
As far as renderpass, it can't be a const ref because of line 120 in VulkanResources.cpp
framebuffer.renderpass = &renderpass;

2023-03-31 23:43 UTC, ZackShrout commented on Engine/Graphics/Vulkan/VulkanResources.h
>  bool create_image(VkDevice device, VkImageType type, u32 width, u32 height, VkFormat format, VkImageTiling tiling, VkImageUsageFlags usage,
It would be! Done.

2023-03-31 23:45 UTC, ZackShrout commented on Engine/Input/InputLinux.cpp
> +	lk_mapping[platform::key_backspace] = input_code::code::key_backspace;
Done

2023-03-31 23:45 UTC, ZackShrout commented on Engine/Input/InputLinux.cpp
> +		right_alt = 0x03,
Yikes... done

2023-03-31 23:47 UTC, ZackShrout commented on Engine/Input/InputLinux.cpp
> +	if (lk_mapping.find(key_sym) == lk_mapping.end())
Nice - done

2023-04-01 00:07 UTC, ZackShrout commented on Engine/Platform/X11Manager.h
> +    key_scrolllock = XK_Scroll_Lock,
Done

2023-04-02 16:11 UTC, abdansyakuuro commented
Wow

2023-04-02 16:53 UTC, Rashmatash approved these changes

2023-04-02 16:54 UTC, Rashmatash commented
Well done! Thanks for your efforts :)

2023-04-02 16:54 UTC, merged